version: '3.7'
services:
  nfs:
    image: nfs-server-alpine
    volumes:
      - /data:/data
    ports:
      - 2049:2049
    priviliedged: true
    networks:
     - proxy
     - internal

networks:
  proxy:
    driver: overlay
    external: true

  internal:
    driver: overlay
    external: true
