version: '3.7'
services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    privileged: true
    volumes:
      - /data:/data
    ports:
      - 2049:2049
    environment:
     - SHARED_DIRECTORY=/data     
    ###deploy:
    ###  placement:
    ##    constraints:
    #      - node.role == manager
 #   networks:
 #    - proxy
 #    - internal



##networks:
##  proxy:
##    driver: overlay
#    external: true
#
 # internal:
#    driver: overlay
#    external: true
