version: '3.7'
services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    volumes:
      - /data:/data
    ports:
      - 2049:2049
    config:
      - nfs-conf
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
     - proxy
     - internal

configs:
  gitlab-configs:
    file: ./nfs.configs
networks:
  proxy:
    driver: overlay
    external: true

  internal:
    driver: overlay
    external: true
