version: '3.7'
services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    volumes:
      - /data:/data
    ports:
      - 2049:2049
    
    deploy:
      placement:
        constraints:
          - node.role == manager
    configs:
     - nfs-config
    networks:
     - proxy
     - internal

configs:
  nfs-config:
    file: ./nfs.configs

networks:
  proxy:
    driver: overlay
    external: true

  internal:
    driver: overlay
    external: true
