version: '3.7'
services:
  nfs:
    image: nfs-server-alpine:latest
    volumes:
      - /data:/data
    ports:
      - 2049:2049
    
    privileged: true
    deploy:
      
      placement:
        constraints:
          - node.role == manager
    networks:
     - proxy
     - internal

networks:
  proxy:
    driver: overlay
    external: true

  internal:
    driver: overlay
    external: true
