version: "3.7"
services:
  traefik:
    image: traefik:1.7-alpine
    command:
      - "--api"
      - "--loglevel=INFO"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=/etc/traefik/acme/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      #- "--acme.onHostRule=true"
      #- "--acme.onDemand=false"
      #- "--acme.email=julien.lebourg@ctg.lu"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=ctg.lu"
      - "--docker.watch"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nfs_acme_traefik:/etc/traefik/acme
    networks:
      - proxy
    ports:
      - 80:80
      #- 443:443
    deploy:
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.frontend.rule=Host:traefik.tina.ctg.lu"
        - "traefik.port=8080"
        - "traefik.backend=traefik"
        - "traefik.frontend.entryPoints=http"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.auth.basic.users=jlebourg:$$apr1$$6A77IGfe$$zH1fYcEOTArJq1/BN2ptd0"
networks:
  proxy:
    driver: overlay
    external: true

volumes:
  nfs_acme_traefik:
    driver_opts:
      type: "nfs"
      o: "addr=tina.ctg.lu,nolock,soft,rw"
      device: ":/data/acme"
