version: '3.7'

services:
  redis:
    image: sameersbn/redis:4.0.9-1
    command:
      - --loglevel warning
    volumes:
      - nfs_gitlab_redis:/var/lib/redis
    networks:
      - proxy

  postgresql:
    image: sameersbn/postgresql:10
    volumes:
     - nfs_gitlab_postgres:/var/lib/postgresql
    environment:
    - DB_USER=gitlab
    - DB_PASS=B186o73l7a
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
    networks:
      - proxy

  gitlab:
    
    image: sameersbn/gitlab:11.2.3
    depends_on:
      - redis
      - postgresql
    deploy:
      labels:
        - "traefik.frontend.rule=Host:gitlab.tina.ctg.lu"
        - "traefik.port=80"
        - "traefik.frontend.entryPoints=http"
        - "traefik.backend=gitlab"
    networks:
      - proxy
    volumes:
      - nfs_gitlab_data:/home/git/data
    environment:
    - DEBUG=false
    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=B186o73l7a
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=Europe/Paris
    - GITLAB_TIMEZONE=Europe/Paris

    #- GITLAB_HTTPS=true
    - GITLAB_HTTPS=false
    - SSL_SELF_SIGNED=false

    - GITLAB_HOST=gitlab.tina.ctg.lu
    - GITLAB_PORT=80
    - GITLAB_SSH_PORT=10022
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_SECRETS_DB_KEY_BASE=B186o73l7a
    - GITLAB_SECRETS_SECRET_KEY_BASE=B186o73l7a
    - GITLAB_SECRETS_OTP_KEY_BASE=B186o73l7a

    - GITLAB_ROOT_PASSWORD=B186o73l7a
    - GITLAB_ROOT_EMAIL=aureussz@gmail.com

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=notifications@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false

    - OAUTH_ENABLED=false
    - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=
    - OAUTH_ALLOW_SSO=
    - OAUTH_BLOCK_AUTO_CREATED_USERS=true
    - OAUTH_AUTO_LINK_LDAP_USER=false
    - OAUTH_AUTO_LINK_SAML_USER=false
    - OAUTH_EXTERNAL_PROVIDERS=

    - OAUTH_CAS3_LABEL=cas3
    - OAUTH_CAS3_SERVER=
    - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=false
    - OAUTH_CAS3_LOGIN_URL=/cas/login
    - OAUTH_CAS3_VALIDATE_URL=/cas/p3/serviceValidate
    - OAUTH_CAS3_LOGOUT_URL=/cas/logout

    - OAUTH_GOOGLE_API_KEY=
    - OAUTH_GOOGLE_APP_SECRET=
    - OAUTH_GOOGLE_RESTRICT_DOMAIN=

    - OAUTH_FACEBOOK_API_KEY=
    - OAUTH_FACEBOOK_APP_SECRET=

    - OAUTH_TWITTER_API_KEY=
    - OAUTH_TWITTER_APP_SECRET=

    - OAUTH_GITHUB_API_KEY=
    - OAUTH_GITHUB_APP_SECRET=
    - OAUTH_GITHUB_URL=
    - OAUTH_GITHUB_VERIFY_SSL=

    - OAUTH_GITLAB_API_KEY=
    - OAUTH_GITLAB_APP_SECRET=

    - OAUTH_BITBUCKET_API_KEY=
    - OAUTH_BITBUCKET_APP_SECRET=

    - OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL=
    - OAUTH_SAML_IDP_CERT_FINGERPRINT=
    - OAUTH_SAML_IDP_SSO_TARGET_URL=
    - OAUTH_SAML_ISSUER=
    - OAUTH_SAML_LABEL="Our SAML Provider"
    - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=urn:oasis:names:tc:SAML:2.0:nameid-format:transient
    - OAUTH_SAML_GROUPS_ATTRIBUTE=
    - OAUTH_SAML_EXTERNAL_GROUPS=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME=

    - OAUTH_CROWD_SERVER_URL=
    - OAUTH_CROWD_APP_NAME=
    - OAUTH_CROWD_APP_PASSWORD=

    - OAUTH_AUTH0_CLIENT_ID=
    - OAUTH_AUTH0_CLIENT_SECRET=
    - OAUTH_AUTH0_DOMAIN=

    - OAUTH_AZURE_API_KEY=
    - OAUTH_AZURE_API_SECRET=
    - OAUTH_AZURE_TENANT_ID=

  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    
    environment:
      - CI_SERVER_URL=https://gitlab.tina.ctg.lu
      - RUNNER_NAME=local-docker-runner
      - REGISTER_NON_INTERACTIVE=true
      - REGISTRATION_TOKEN=4YMExUDadrAXer-4aJ4x
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE=ubuntu:artful
      - REGISTER_LOCKED=false
   
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nfs_runner_etc:/etc/gitlab-runner
      - nfs_runner_home:/home/gitlab-runner


networks:
  proxy:
    driver: overlay
    external: true

volumes:
  nfs_runner_etc:
    driver_opts:
      type: "nfs"
      o: "addr=tina.ctg.lu,nolock,soft,rw"
      device: ":/data/runner/etc/gitlab_runner"

  nfs_runner_home:
    driver_opts:
      type: "nfs"
      o: "addr=tina.ctg.lu,nolock,soft,rw"
      device: ":/data/runner/home/gitlab_runner"

  nfs_gitlab_postgres:
    driver_opts:
      type: "nfs"
      o: "addr=tina.ctg.lu,nolock,soft,rw"
      device: ":/data/gitlab/postgres"

  nfs_gitlab_data:
    driver_opts:
      type: "nfs"
      o: "addr=tina.ctg.lu,nolock,soft,rw"
      device: ":/data/gitlab/data"

  nfs_gitlab_redis:
    driver_opts:
      type: "nfs"
      o: "addr=tina.ctg.lu,nolock,soft,rw"
      device: ":/data/gitlab/redis"

      









