version: "3.2"
services:
  portainer:
    image: portainer/portainer:1.19.2

    volumes:
      - nfs_portainer:/data
    networks:
      - portainer_agent
      - externe
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.frontend.rule=Host:portainer.mytools.live"
        - "traefik.port=9000"
        - "traefik.backend=portainer"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.docker.network=externe"

  agent:
    image: portainer/agent:1.1.2
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]


networks:
  portainer_agent:
    driver: overlay
    attachable: true
  externe:
    attachable: true
    driver: overlay
    external: true

volumes:
  nfs_portainer:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.183,nolock,soft,rw"
      device: ":/data/portainer"


